export const WRONG_CHAIN_MESSAGE = process.env.REACT_APP_WRONG_CHAIN_MESSAGE;
export const SUPPORTED_CHAIN_IDS = process.env.REACT_APP_SUPPORTED_CHAIN_IDS;
export const stableCoinSymbols = process.env.REACT_APP_STABLE_COIN_SYMBOLS;
export const stableCoinAddresses = process.env.REACT_APP_STABLE_COIN_ADDRESSES;
export const stableCoinDecimals = process.env.REACT_APP_STABLE_COIN_DECIMALS;

export const stableCoinListConfig = stableCoinSymbols.split(',').map((symbol, index) => {
	  return {
		  stableCoin: symbol,
		  stableCoinAdd: stableCoinAddresses.split(',')[index],
		  stableCoinDecimal: stableCoinDecimals.split(',')[index]
									  }					
									  });


//ETHEREUM
export const GRAPHAPIURL_MASTER_ETHEREUM =
	process.env.REACT_APP_GRAPHAPIURL_LEND_ETHEREUM;
export const CONTRACT_ADDRESS_MASTER_ETHEREUM =
	process.env.REACT_APP_MASTER_CONTRACT_ADDRESS_ETHEREUM;
export const CONTRACT_ADDRESS_ORACLE_ETHEREUM =
	process.env.REACT_APP_ORACLE_CONTRACT_ADDRESS_ETHEREUM;
export const CONTRACT_ADDRESS_LEND_ETHEREUM =
	process.env.REACT_APP_LEND_CONTRACT_ADDRESS_ETHEREUM;
export const ETHEREUM_CHAIN_ID = process.env.REACT_APP_ETHEREUM_CHAIN_ID;


//BSC
export const GRAPHAPIURL_MASTER_BSC =
	process.env.REACT_APP_GRAPHAPIURL_LEND_BSC;
export const CONTRACT_ADDRESS_MASTER_BSC =
	process.env.REACT_APP_MASTER_CONTRACT_ADDRESS_BSC;
export const CONTRACT_ADDRESS_ORACLE_BSC =
	process.env.REACT_APP_ORACLE_CONTRACT_ADDRESS_BSC;
export const CONTRACT_ADDRESS_LEND_BSC =
	process.env.REACT_APP_LEND_CONTRACT_ADDRESS_BSC;
export const BSC_CHAIN_ID = process.env.REACT_APP_BSC_CHAIN_ID;

//POLYGON
export const GRAPHAPIURL_MASTER_POLYGON =
	process.env.REACT_APP_GRAPHAPIURL_LEND_POLYGON;
export const CONTRACT_ADDRESS_MASTER_POLYGON =
	process.env.REACT_APP_MASTER_CONTRACT_ADDRESS_POLYGON;
export const CONTRACT_ADDRESS_ORACLE_POLYGON =
	process.env.REACT_APP_ORACLE_CONTRACT_ADDRESS_POLYGON;
export const CONTRACT_ADDRESS_LEND_POLYGON =
	process.env.REACT_APP_LEND_CONTRACT_ADDRESS_POLYGON;
export const POLYGON_CHAIN_ID = process.env.REACT_APP_POLYGON_CHAIN_ID;

//AVALANCHE
export const GRAPHAPIURL_MASTER_AVALANCHE =
	process.env.REACT_APP_GRAPHAPIURL_LEND_AVALANCHE;
export const CONTRACT_ADDRESS_MASTER_AVALANCHE =
	process.env.REACT_APP_MASTER_CONTRACT_ADDRESS_AVALANCHE;
export const CONTRACT_ADDRESS_ORACLE_AVALANCHE =
	process.env.REACT_APP_ORACLE_CONTRACT_ADDRESS_AVALANCHE;
export const CONTRACT_ADDRESS_LEND_AVALANCHE =
	process.env.REACT_APP_LEND_CONTRACT_ADDRESS_AVALANCHE;
export const AVALANCHE_CHAIN_ID = process.env.REACT_APP_AVALANCHE_CHAIN_ID;
