export const WRONG_CHAIN_MESSAGE = process.env.REACT_APP_WRONG_CHAIN_MESSAGE;
export const SUPPORTED_CHAIN_IDS = process.env.REACT_APP_SUPPORTED_CHAIN_IDS;

export const ETHEREUM_LEND_URI =
	process.env.REACT_APP_GRAPHAPIURL_LEND_ETHEREUM;
